/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: adamio.i

package adamio

/*

#cgo CFLAGS: -std=c99
#cgo LDFLAGS: -L. -l:libbio5630io.so

#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef int intgo;
typedef unsigned int uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef long long swig_type_2;
extern void _wrap_Swig_free_adamio_c137db358c285f21(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_adamio_c137db358c285f21(swig_intgo arg1);
extern swig_intgo _wrap_MODULEID_5017_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5018_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5013A_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5013B_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5017H_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5017UH_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5018P_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5024_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5050_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5051_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5052_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5053_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5055_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5056_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5057_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5060_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5068_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5069_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5080_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_5081_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_UNDEFINE_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_MODULEID_MASK_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Hz_60_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Hz_50_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_OMIT_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg15To15_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg10To10_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg5To5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg2pt5To2pt5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg1pt25To1pt25_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg1To1_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To15_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To10_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To2pt5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To1pt25_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_0To1_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg625To625_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg500To500_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg312pt5To312pt5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg200To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg150To150_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg100To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg50To50_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg30To30_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg20To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg15To15_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg10To10_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_Neg5To5_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To625_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To500_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To150_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To50_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To15_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mV_0To10_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mA_Neg20To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mA_0To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mA_4To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_mA_0To24_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg2To2_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg4To4_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_Neg20To20_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Jtype_0To760C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ktype_0To1370C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ttype_Neg100To400C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Etype_0To1000C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Rtype_500To1750C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Stype_500To1750C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Btype_500To1800C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_Neg50To150_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_Neg200To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_0To400_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_Neg50To150_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_Neg100To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_0To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt385_0To600_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_Neg100To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_0To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_0To600_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_0To400_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt392_Neg200To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Pt1000_Neg40To160_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Balcon500_Neg30To120_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ni518_Neg80To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ni518_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ni508_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ni508_Neg50To200_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Thermistor_3K_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Thermistor_10K_0To100_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Jtype_Neg210To1200C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ktype_Neg270To1372C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ttype_Neg270To400C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Etype_Neg270To1000C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Rtype_Neg50To1768C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Stype_Neg50To1768C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Btype_40To1820C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Jtype_Neg210To870C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Rtype_0To1768C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Stype_0To1768C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ttype_Neg20To135C_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_UserCustomizedVrgStart_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_UserCustomizedVrgEnd_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_ExternalRefBipolar_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_V_ExternalRefUnipolar_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ContrMod_Bi_DIR_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ContrMod_UP_DOWN_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ContrMod_UP_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ContrMod_Freq_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_AbPhaseX1_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_AbPhaseX2_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_AbPhaseX4_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_EngineerUnit_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Percent_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_TwosComplementHex_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Ohms_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Unknown_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_Zero_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_Span_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_Cjc_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_4mA_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_20mA_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Cali_Trim_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ReadOnly_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Writable_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Modal_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Nature_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_Success_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningIntrNotAvailable_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningParamOutOfRange_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningPropValueOutOfRange_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningPropValueNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningPropValueConflict_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_WarningVrgOfGroupNotSame_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorHandleNotValid_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorParamOutOfRange_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorParamNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorParamFmtUnexpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorMemoryNotEnough_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorBufferIsNull_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorBufferTooSmall_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDataLenExceedLimit_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorFuncNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorEventNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPropNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPropReadOnly_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPropValueConflict_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPropValueOutOfRange_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPropValueNotSpted_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPrivilegeNotHeld_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorPrivilegeNotAvailable_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDriverNotFound_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDriverVerMismatch_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDriverCountExceedLimit_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDeviceNotOpened_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDeviceNotExist_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDeviceUnrecognized_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorConfigDataLost_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorFuncNotInited_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorFuncBusy_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorIntrNotAvailable_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDmaNotAvailable_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorDeviceIoTimeOut_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorSignatureNotMatch_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ErrorUndefined_adamio_c137db358c285f21(void);
extern swig_intgo _wrap_ADAMDrvOpen_adamio_c137db358c285f21(swig_voidp arg1);
extern swig_intgo _wrap_ADAMDrvClose_adamio_c137db358c285f21(swig_voidp arg1);
extern swig_intgo _wrap_SYS_GetNodeID_adamio_c137db358c285f21(swig_intgo arg1, swig_voidp arg2);
extern swig_intgo _wrap_SYS_GetModuleID_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_SYS_GetModuleName_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_type_1 arg3);
extern swig_intgo _wrap_AI_GetChannelTotal_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AI_GetChannelEnabled_adamio_c137db358c285f21(swig_intgo arg1, short arg2, char* arg3);
extern swig_intgo _wrap_AI_SetChannelEnabled_adamio_c137db358c285f21(swig_intgo arg1, short arg2, char* arg3);
extern swig_intgo _wrap_AI_GetInputRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_AI_SetInputRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_AI_GetRangeIntegrationTime_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AI_SetRangeIntegrationTime_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_AI_GetDataFormat_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AI_SetDataFormat_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_AI_GetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, unsigned short* arg3, double* arg4);
extern swig_intgo _wrap_AI_GetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, uintptr_t arg4, swig_voidp arg5);
extern swig_intgo _wrap_AI_Calibration_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_AI_Calibration_CJC_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, float arg5);
extern swig_intgo _wrap_AO_GetChannelTotal_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AO_GetOutputRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_AO_SetOutputRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_AO_GetStartup_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_AO_SetStartup_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, double arg4);
extern swig_intgo _wrap_AO_GetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AO_GetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_AO_SetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_AO_SetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, double arg4);
extern swig_intgo _wrap_AO_Calibration_4mA_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_AO_Calibration_20mA_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_AO_Calibration_Trim_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_type_2 arg4);
extern swig_intgo _wrap_DIO_GetChannelTotal_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_DI_GetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_DI_GetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_DIO_GetUniversalStatus_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_DI_GetInvert_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_DI_SetInvert_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_DO_SetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, _Bool arg4);
extern swig_intgo _wrap_DO_SetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_intgo arg3);
extern swig_intgo _wrap_DO_GetValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_CNT_GetValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_ClearValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_CNT_GetRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetRange_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_CNT_GetFilter_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_CNT_SetFilter_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_intgo arg3);
extern swig_intgo _wrap_CNT_GetStartup_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetStartup_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_intgo arg4);
extern swig_intgo _wrap_CNT_GetState_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetState_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, _Bool arg4);
extern swig_intgo _wrap_CNT_GetOverflow_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_ClearOverflow_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_CNT_GetAlarmFlag_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_ClearAlarmFlag_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3);
extern swig_intgo _wrap_CNT_GetAlarmType_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetAlarmType_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_CNT_GetAlarmEnable_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetAlarmEnable_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, _Bool arg4);
extern swig_intgo _wrap_CNT_GetAlarmMap_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetAlarmMap_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_CNT_GetAlarmLimit_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetAlarmLimit_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_intgo arg4);
extern swig_intgo _wrap_CNT_GetDoValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, swig_voidp arg4);
extern swig_intgo _wrap_CNT_SetDoValue_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, _Bool arg4);
extern swig_intgo _wrap_CNT_GetDoValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_CNT_SetDoValues_adamio_c137db358c285f21(swig_intgo arg1, short arg2, char arg3);
extern swig_intgo _wrap_CNT_GetFreqAcqTime_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
extern swig_intgo _wrap_CNT_SetFreqAcqTime_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_intgo arg3);
extern swig_intgo _wrap_CNT_GetRemoteAlarmFlag_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, swig_voidp arg5);
extern swig_intgo _wrap_CNT_ClearRemoteAlarmFlag_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4);
extern swig_intgo _wrap_CNT_GetRemoteAlarmEnable_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, swig_voidp arg5);
extern swig_intgo _wrap_CNT_SetRemoteAlarmEnable_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, _Bool arg5);
extern swig_intgo _wrap_CNT_GetRemoteAlarmMap_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, swig_voidp arg5, swig_voidp arg6);
extern swig_intgo _wrap_CNT_SetRemoteAlarmMap_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, short arg5, short arg6);
extern swig_intgo _wrap_CNT_GetRemoteAlarmLimit_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, swig_voidp arg5);
extern swig_intgo _wrap_CNT_SetRemoteAlarmLimit_adamio_c137db358c285f21(swig_intgo arg1, short arg2, short arg3, char arg4, swig_intgo arg5);
extern swig_intgo _wrap_CNT_GetFwVersion_adamio_c137db358c285f21(swig_intgo arg1, short arg2, swig_voidp arg3);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_adamio_c137db358c285f21(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Enum_SS_tagModuleId int
func _swig_getMODULEID_5017() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5017_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5017 Enum_SS_tagModuleId = _swig_getMODULEID_5017()
func _swig_getMODULEID_5018() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5018_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5018 Enum_SS_tagModuleId = _swig_getMODULEID_5018()
func _swig_getMODULEID_5013A() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5013A_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5013A Enum_SS_tagModuleId = _swig_getMODULEID_5013A()
func _swig_getMODULEID_5013B() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5013B_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5013B Enum_SS_tagModuleId = _swig_getMODULEID_5013B()
func _swig_getMODULEID_5017H() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5017H_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5017H Enum_SS_tagModuleId = _swig_getMODULEID_5017H()
func _swig_getMODULEID_5017UH() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5017UH_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5017UH Enum_SS_tagModuleId = _swig_getMODULEID_5017UH()
func _swig_getMODULEID_5018P() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5018P_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5018P Enum_SS_tagModuleId = _swig_getMODULEID_5018P()
func _swig_getMODULEID_5024() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5024_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5024 Enum_SS_tagModuleId = _swig_getMODULEID_5024()
func _swig_getMODULEID_5050() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5050_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5050 Enum_SS_tagModuleId = _swig_getMODULEID_5050()
func _swig_getMODULEID_5051() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5051_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5051 Enum_SS_tagModuleId = _swig_getMODULEID_5051()
func _swig_getMODULEID_5052() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5052_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5052 Enum_SS_tagModuleId = _swig_getMODULEID_5052()
func _swig_getMODULEID_5053() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5053_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5053 Enum_SS_tagModuleId = _swig_getMODULEID_5053()
func _swig_getMODULEID_5055() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5055_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5055 Enum_SS_tagModuleId = _swig_getMODULEID_5055()
func _swig_getMODULEID_5056() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5056_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5056 Enum_SS_tagModuleId = _swig_getMODULEID_5056()
func _swig_getMODULEID_5057() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5057_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5057 Enum_SS_tagModuleId = _swig_getMODULEID_5057()
func _swig_getMODULEID_5060() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5060_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5060 Enum_SS_tagModuleId = _swig_getMODULEID_5060()
func _swig_getMODULEID_5068() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5068_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5068 Enum_SS_tagModuleId = _swig_getMODULEID_5068()
func _swig_getMODULEID_5069() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5069_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5069 Enum_SS_tagModuleId = _swig_getMODULEID_5069()
func _swig_getMODULEID_5080() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5080_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5080 Enum_SS_tagModuleId = _swig_getMODULEID_5080()
func _swig_getMODULEID_5081() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_5081_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_5081 Enum_SS_tagModuleId = _swig_getMODULEID_5081()
func _swig_getMODULEID_UNDEFINE() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_UNDEFINE_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_UNDEFINE Enum_SS_tagModuleId = _swig_getMODULEID_UNDEFINE()
func _swig_getMODULEID_MASK() (_swig_ret Enum_SS_tagModuleId) {
	var swig_r Enum_SS_tagModuleId
	swig_r = (Enum_SS_tagModuleId)(C._wrap_MODULEID_MASK_adamio_c137db358c285f21())
	return swig_r
}

var MODULEID_MASK Enum_SS_tagModuleId = _swig_getMODULEID_MASK()
type Enum_SS_tagAiIntegrationTime int
func _swig_getHz_60() (_swig_ret Enum_SS_tagAiIntegrationTime) {
	var swig_r Enum_SS_tagAiIntegrationTime
	swig_r = (Enum_SS_tagAiIntegrationTime)(C._wrap_Hz_60_adamio_c137db358c285f21())
	return swig_r
}

var Hz_60 Enum_SS_tagAiIntegrationTime = _swig_getHz_60()
func _swig_getHz_50() (_swig_ret Enum_SS_tagAiIntegrationTime) {
	var swig_r Enum_SS_tagAiIntegrationTime
	swig_r = (Enum_SS_tagAiIntegrationTime)(C._wrap_Hz_50_adamio_c137db358c285f21())
	return swig_r
}

var Hz_50 Enum_SS_tagAiIntegrationTime = _swig_getHz_50()
type Enum_SS_tagValueRange int
func _swig_getV_OMIT() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_OMIT_adamio_c137db358c285f21())
	return swig_r
}

var V_OMIT Enum_SS_tagValueRange = _swig_getV_OMIT()
func _swig_getV_Neg15To15() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg15To15_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg15To15 Enum_SS_tagValueRange = _swig_getV_Neg15To15()
func _swig_getV_Neg10To10() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg10To10_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg10To10 Enum_SS_tagValueRange = _swig_getV_Neg10To10()
func _swig_getV_Neg5To5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg5To5_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg5To5 Enum_SS_tagValueRange = _swig_getV_Neg5To5()
func _swig_getV_Neg2pt5To2pt5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg2pt5To2pt5_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg2pt5To2pt5 Enum_SS_tagValueRange = _swig_getV_Neg2pt5To2pt5()
func _swig_getV_Neg1pt25To1pt25() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg1pt25To1pt25_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg1pt25To1pt25 Enum_SS_tagValueRange = _swig_getV_Neg1pt25To1pt25()
func _swig_getV_Neg1To1() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg1To1_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg1To1 Enum_SS_tagValueRange = _swig_getV_Neg1To1()
func _swig_getV_0To15() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To15_adamio_c137db358c285f21())
	return swig_r
}

var V_0To15 Enum_SS_tagValueRange = _swig_getV_0To15()
func _swig_getV_0To10() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To10_adamio_c137db358c285f21())
	return swig_r
}

var V_0To10 Enum_SS_tagValueRange = _swig_getV_0To10()
func _swig_getV_0To5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To5_adamio_c137db358c285f21())
	return swig_r
}

var V_0To5 Enum_SS_tagValueRange = _swig_getV_0To5()
func _swig_getV_0To2pt5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To2pt5_adamio_c137db358c285f21())
	return swig_r
}

var V_0To2pt5 Enum_SS_tagValueRange = _swig_getV_0To2pt5()
func _swig_getV_0To1pt25() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To1pt25_adamio_c137db358c285f21())
	return swig_r
}

var V_0To1pt25 Enum_SS_tagValueRange = _swig_getV_0To1pt25()
func _swig_getV_0To1() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_0To1_adamio_c137db358c285f21())
	return swig_r
}

var V_0To1 Enum_SS_tagValueRange = _swig_getV_0To1()
func _swig_getmV_Neg625To625() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg625To625_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg625To625 Enum_SS_tagValueRange = _swig_getmV_Neg625To625()
func _swig_getmV_Neg500To500() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg500To500_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg500To500 Enum_SS_tagValueRange = _swig_getmV_Neg500To500()
func _swig_getmV_Neg312pt5To312pt5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg312pt5To312pt5_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg312pt5To312pt5 Enum_SS_tagValueRange = _swig_getmV_Neg312pt5To312pt5()
func _swig_getmV_Neg200To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg200To200_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg200To200 Enum_SS_tagValueRange = _swig_getmV_Neg200To200()
func _swig_getmV_Neg150To150() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg150To150_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg150To150 Enum_SS_tagValueRange = _swig_getmV_Neg150To150()
func _swig_getmV_Neg100To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg100To100_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg100To100 Enum_SS_tagValueRange = _swig_getmV_Neg100To100()
func _swig_getmV_Neg50To50() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg50To50_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg50To50 Enum_SS_tagValueRange = _swig_getmV_Neg50To50()
func _swig_getmV_Neg30To30() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg30To30_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg30To30 Enum_SS_tagValueRange = _swig_getmV_Neg30To30()
func _swig_getmV_Neg20To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg20To20_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg20To20 Enum_SS_tagValueRange = _swig_getmV_Neg20To20()
func _swig_getmV_Neg15To15() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg15To15_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg15To15 Enum_SS_tagValueRange = _swig_getmV_Neg15To15()
func _swig_getmV_Neg10To10() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg10To10_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg10To10 Enum_SS_tagValueRange = _swig_getmV_Neg10To10()
func _swig_getmV_Neg5To5() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_Neg5To5_adamio_c137db358c285f21())
	return swig_r
}

var MV_Neg5To5 Enum_SS_tagValueRange = _swig_getmV_Neg5To5()
func _swig_getmV_0To625() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To625_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To625 Enum_SS_tagValueRange = _swig_getmV_0To625()
func _swig_getmV_0To500() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To500_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To500 Enum_SS_tagValueRange = _swig_getmV_0To500()
func _swig_getmV_0To150() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To150_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To150 Enum_SS_tagValueRange = _swig_getmV_0To150()
func _swig_getmV_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To100_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To100 Enum_SS_tagValueRange = _swig_getmV_0To100()
func _swig_getmV_0To50() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To50_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To50 Enum_SS_tagValueRange = _swig_getmV_0To50()
func _swig_getmV_0To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To20_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To20 Enum_SS_tagValueRange = _swig_getmV_0To20()
func _swig_getmV_0To15() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To15_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To15 Enum_SS_tagValueRange = _swig_getmV_0To15()
func _swig_getmV_0To10() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mV_0To10_adamio_c137db358c285f21())
	return swig_r
}

var MV_0To10 Enum_SS_tagValueRange = _swig_getmV_0To10()
func _swig_getmA_Neg20To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mA_Neg20To20_adamio_c137db358c285f21())
	return swig_r
}

var MA_Neg20To20 Enum_SS_tagValueRange = _swig_getmA_Neg20To20()
func _swig_getmA_0To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mA_0To20_adamio_c137db358c285f21())
	return swig_r
}

var MA_0To20 Enum_SS_tagValueRange = _swig_getmA_0To20()
func _swig_getmA_4To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mA_4To20_adamio_c137db358c285f21())
	return swig_r
}

var MA_4To20 Enum_SS_tagValueRange = _swig_getmA_4To20()
func _swig_getmA_0To24() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_mA_0To24_adamio_c137db358c285f21())
	return swig_r
}

var MA_0To24 Enum_SS_tagValueRange = _swig_getmA_0To24()
func _swig_getV_Neg2To2() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg2To2_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg2To2 Enum_SS_tagValueRange = _swig_getV_Neg2To2()
func _swig_getV_Neg4To4() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg4To4_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg4To4 Enum_SS_tagValueRange = _swig_getV_Neg4To4()
func _swig_getV_Neg20To20() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_Neg20To20_adamio_c137db358c285f21())
	return swig_r
}

var V_Neg20To20 Enum_SS_tagValueRange = _swig_getV_Neg20To20()
func _swig_getJtype_0To760C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Jtype_0To760C_adamio_c137db358c285f21())
	return swig_r
}

var Jtype_0To760C Enum_SS_tagValueRange = _swig_getJtype_0To760C()
func _swig_getKtype_0To1370C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ktype_0To1370C_adamio_c137db358c285f21())
	return swig_r
}

var Ktype_0To1370C Enum_SS_tagValueRange = _swig_getKtype_0To1370C()
func _swig_getTtype_Neg100To400C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ttype_Neg100To400C_adamio_c137db358c285f21())
	return swig_r
}

var Ttype_Neg100To400C Enum_SS_tagValueRange = _swig_getTtype_Neg100To400C()
func _swig_getEtype_0To1000C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Etype_0To1000C_adamio_c137db358c285f21())
	return swig_r
}

var Etype_0To1000C Enum_SS_tagValueRange = _swig_getEtype_0To1000C()
func _swig_getRtype_500To1750C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Rtype_500To1750C_adamio_c137db358c285f21())
	return swig_r
}

var Rtype_500To1750C Enum_SS_tagValueRange = _swig_getRtype_500To1750C()
func _swig_getStype_500To1750C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Stype_500To1750C_adamio_c137db358c285f21())
	return swig_r
}

var Stype_500To1750C Enum_SS_tagValueRange = _swig_getStype_500To1750C()
func _swig_getBtype_500To1800C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Btype_500To1800C_adamio_c137db358c285f21())
	return swig_r
}

var Btype_500To1800C Enum_SS_tagValueRange = _swig_getBtype_500To1800C()
func _swig_getPt392_Neg50To150() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_Neg50To150_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_Neg50To150 Enum_SS_tagValueRange = _swig_getPt392_Neg50To150()
func _swig_getPt385_Neg200To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_Neg200To200_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_Neg200To200 Enum_SS_tagValueRange = _swig_getPt385_Neg200To200()
func _swig_getPt385_0To400() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_0To400_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_0To400 Enum_SS_tagValueRange = _swig_getPt385_0To400()
func _swig_getPt385_Neg50To150() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_Neg50To150_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_Neg50To150 Enum_SS_tagValueRange = _swig_getPt385_Neg50To150()
func _swig_getPt385_Neg100To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_Neg100To100_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_Neg100To100 Enum_SS_tagValueRange = _swig_getPt385_Neg100To100()
func _swig_getPt385_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_0To100 Enum_SS_tagValueRange = _swig_getPt385_0To100()
func _swig_getPt385_0To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_0To200_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_0To200 Enum_SS_tagValueRange = _swig_getPt385_0To200()
func _swig_getPt385_0To600() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt385_0To600_adamio_c137db358c285f21())
	return swig_r
}

var Pt385_0To600 Enum_SS_tagValueRange = _swig_getPt385_0To600()
func _swig_getPt392_Neg100To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_Neg100To100_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_Neg100To100 Enum_SS_tagValueRange = _swig_getPt392_Neg100To100()
func _swig_getPt392_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_0To100 Enum_SS_tagValueRange = _swig_getPt392_0To100()
func _swig_getPt392_0To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_0To200_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_0To200 Enum_SS_tagValueRange = _swig_getPt392_0To200()
func _swig_getPt392_0To600() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_0To600_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_0To600 Enum_SS_tagValueRange = _swig_getPt392_0To600()
func _swig_getPt392_0To400() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_0To400_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_0To400 Enum_SS_tagValueRange = _swig_getPt392_0To400()
func _swig_getPt392_Neg200To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt392_Neg200To200_adamio_c137db358c285f21())
	return swig_r
}

var Pt392_Neg200To200 Enum_SS_tagValueRange = _swig_getPt392_Neg200To200()
func _swig_getPt1000_Neg40To160() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Pt1000_Neg40To160_adamio_c137db358c285f21())
	return swig_r
}

var Pt1000_Neg40To160 Enum_SS_tagValueRange = _swig_getPt1000_Neg40To160()
func _swig_getBalcon500_Neg30To120() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Balcon500_Neg30To120_adamio_c137db358c285f21())
	return swig_r
}

var Balcon500_Neg30To120 Enum_SS_tagValueRange = _swig_getBalcon500_Neg30To120()
func _swig_getNi518_Neg80To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ni518_Neg80To100_adamio_c137db358c285f21())
	return swig_r
}

var Ni518_Neg80To100 Enum_SS_tagValueRange = _swig_getNi518_Neg80To100()
func _swig_getNi518_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ni518_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Ni518_0To100 Enum_SS_tagValueRange = _swig_getNi518_0To100()
func _swig_getNi508_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ni508_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Ni508_0To100 Enum_SS_tagValueRange = _swig_getNi508_0To100()
func _swig_getNi508_Neg50To200() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ni508_Neg50To200_adamio_c137db358c285f21())
	return swig_r
}

var Ni508_Neg50To200 Enum_SS_tagValueRange = _swig_getNi508_Neg50To200()
func _swig_getThermistor_3K_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Thermistor_3K_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Thermistor_3K_0To100 Enum_SS_tagValueRange = _swig_getThermistor_3K_0To100()
func _swig_getThermistor_10K_0To100() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Thermistor_10K_0To100_adamio_c137db358c285f21())
	return swig_r
}

var Thermistor_10K_0To100 Enum_SS_tagValueRange = _swig_getThermistor_10K_0To100()
func _swig_getJtype_Neg210To1200C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Jtype_Neg210To1200C_adamio_c137db358c285f21())
	return swig_r
}

var Jtype_Neg210To1200C Enum_SS_tagValueRange = _swig_getJtype_Neg210To1200C()
func _swig_getKtype_Neg270To1372C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ktype_Neg270To1372C_adamio_c137db358c285f21())
	return swig_r
}

var Ktype_Neg270To1372C Enum_SS_tagValueRange = _swig_getKtype_Neg270To1372C()
func _swig_getTtype_Neg270To400C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ttype_Neg270To400C_adamio_c137db358c285f21())
	return swig_r
}

var Ttype_Neg270To400C Enum_SS_tagValueRange = _swig_getTtype_Neg270To400C()
func _swig_getEtype_Neg270To1000C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Etype_Neg270To1000C_adamio_c137db358c285f21())
	return swig_r
}

var Etype_Neg270To1000C Enum_SS_tagValueRange = _swig_getEtype_Neg270To1000C()
func _swig_getRtype_Neg50To1768C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Rtype_Neg50To1768C_adamio_c137db358c285f21())
	return swig_r
}

var Rtype_Neg50To1768C Enum_SS_tagValueRange = _swig_getRtype_Neg50To1768C()
func _swig_getStype_Neg50To1768C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Stype_Neg50To1768C_adamio_c137db358c285f21())
	return swig_r
}

var Stype_Neg50To1768C Enum_SS_tagValueRange = _swig_getStype_Neg50To1768C()
func _swig_getBtype_40To1820C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Btype_40To1820C_adamio_c137db358c285f21())
	return swig_r
}

var Btype_40To1820C Enum_SS_tagValueRange = _swig_getBtype_40To1820C()
func _swig_getJtype_Neg210To870C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Jtype_Neg210To870C_adamio_c137db358c285f21())
	return swig_r
}

var Jtype_Neg210To870C Enum_SS_tagValueRange = _swig_getJtype_Neg210To870C()
func _swig_getRtype_0To1768C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Rtype_0To1768C_adamio_c137db358c285f21())
	return swig_r
}

var Rtype_0To1768C Enum_SS_tagValueRange = _swig_getRtype_0To1768C()
func _swig_getStype_0To1768C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Stype_0To1768C_adamio_c137db358c285f21())
	return swig_r
}

var Stype_0To1768C Enum_SS_tagValueRange = _swig_getStype_0To1768C()
func _swig_getTtype_Neg20To135C() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_Ttype_Neg20To135C_adamio_c137db358c285f21())
	return swig_r
}

var Ttype_Neg20To135C Enum_SS_tagValueRange = _swig_getTtype_Neg20To135C()
func _swig_getUserCustomizedVrgStart() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_UserCustomizedVrgStart_adamio_c137db358c285f21())
	return swig_r
}

var UserCustomizedVrgStart Enum_SS_tagValueRange = _swig_getUserCustomizedVrgStart()
func _swig_getUserCustomizedVrgEnd() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_UserCustomizedVrgEnd_adamio_c137db358c285f21())
	return swig_r
}

var UserCustomizedVrgEnd Enum_SS_tagValueRange = _swig_getUserCustomizedVrgEnd()
func _swig_getV_ExternalRefBipolar() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_ExternalRefBipolar_adamio_c137db358c285f21())
	return swig_r
}

var V_ExternalRefBipolar Enum_SS_tagValueRange = _swig_getV_ExternalRefBipolar()
func _swig_getV_ExternalRefUnipolar() (_swig_ret Enum_SS_tagValueRange) {
	var swig_r Enum_SS_tagValueRange
	swig_r = (Enum_SS_tagValueRange)(C._wrap_V_ExternalRefUnipolar_adamio_c137db358c285f21())
	return swig_r
}

var V_ExternalRefUnipolar Enum_SS_tagValueRange = _swig_getV_ExternalRefUnipolar()
type Enum_SS_tagSignalCountingType int
func _swig_getContrMod_Bi_DIR() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_ContrMod_Bi_DIR_adamio_c137db358c285f21())
	return swig_r
}

var ContrMod_Bi_DIR Enum_SS_tagSignalCountingType = _swig_getContrMod_Bi_DIR()
func _swig_getContrMod_UP_DOWN() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_ContrMod_UP_DOWN_adamio_c137db358c285f21())
	return swig_r
}

var ContrMod_UP_DOWN Enum_SS_tagSignalCountingType = _swig_getContrMod_UP_DOWN()
func _swig_getContrMod_UP() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_ContrMod_UP_adamio_c137db358c285f21())
	return swig_r
}

var ContrMod_UP Enum_SS_tagSignalCountingType = _swig_getContrMod_UP()
func _swig_getContrMod_Freq() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_ContrMod_Freq_adamio_c137db358c285f21())
	return swig_r
}

var ContrMod_Freq Enum_SS_tagSignalCountingType = _swig_getContrMod_Freq()
func _swig_getAbPhaseX1() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_AbPhaseX1_adamio_c137db358c285f21())
	return swig_r
}

var AbPhaseX1 Enum_SS_tagSignalCountingType = _swig_getAbPhaseX1()
func _swig_getAbPhaseX2() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_AbPhaseX2_adamio_c137db358c285f21())
	return swig_r
}

var AbPhaseX2 Enum_SS_tagSignalCountingType = _swig_getAbPhaseX2()
func _swig_getAbPhaseX4() (_swig_ret Enum_SS_tagSignalCountingType) {
	var swig_r Enum_SS_tagSignalCountingType
	swig_r = (Enum_SS_tagSignalCountingType)(C._wrap_AbPhaseX4_adamio_c137db358c285f21())
	return swig_r
}

var AbPhaseX4 Enum_SS_tagSignalCountingType = _swig_getAbPhaseX4()
type Enum_SS_tagAIDataUnit int
func _swig_getEngineerUnit() (_swig_ret Enum_SS_tagAIDataUnit) {
	var swig_r Enum_SS_tagAIDataUnit
	swig_r = (Enum_SS_tagAIDataUnit)(C._wrap_EngineerUnit_adamio_c137db358c285f21())
	return swig_r
}

var EngineerUnit Enum_SS_tagAIDataUnit = _swig_getEngineerUnit()
func _swig_getPercent() (_swig_ret Enum_SS_tagAIDataUnit) {
	var swig_r Enum_SS_tagAIDataUnit
	swig_r = (Enum_SS_tagAIDataUnit)(C._wrap_Percent_adamio_c137db358c285f21())
	return swig_r
}

var Percent Enum_SS_tagAIDataUnit = _swig_getPercent()
func _swig_getTwosComplementHex() (_swig_ret Enum_SS_tagAIDataUnit) {
	var swig_r Enum_SS_tagAIDataUnit
	swig_r = (Enum_SS_tagAIDataUnit)(C._wrap_TwosComplementHex_adamio_c137db358c285f21())
	return swig_r
}

var TwosComplementHex Enum_SS_tagAIDataUnit = _swig_getTwosComplementHex()
func _swig_getOhms() (_swig_ret Enum_SS_tagAIDataUnit) {
	var swig_r Enum_SS_tagAIDataUnit
	swig_r = (Enum_SS_tagAIDataUnit)(C._wrap_Ohms_adamio_c137db358c285f21())
	return swig_r
}

var Ohms Enum_SS_tagAIDataUnit = _swig_getOhms()
func _swig_getUnknown() (_swig_ret Enum_SS_tagAIDataUnit) {
	var swig_r Enum_SS_tagAIDataUnit
	swig_r = (Enum_SS_tagAIDataUnit)(C._wrap_Unknown_adamio_c137db358c285f21())
	return swig_r
}

var Unknown Enum_SS_tagAIDataUnit = _swig_getUnknown()
type Enum_SS_AI_CALI_MODE int
func _swig_getCali_Zero() (_swig_ret Enum_SS_AI_CALI_MODE) {
	var swig_r Enum_SS_AI_CALI_MODE
	swig_r = (Enum_SS_AI_CALI_MODE)(C._wrap_Cali_Zero_adamio_c137db358c285f21())
	return swig_r
}

var Cali_Zero Enum_SS_AI_CALI_MODE = _swig_getCali_Zero()
func _swig_getCali_Span() (_swig_ret Enum_SS_AI_CALI_MODE) {
	var swig_r Enum_SS_AI_CALI_MODE
	swig_r = (Enum_SS_AI_CALI_MODE)(C._wrap_Cali_Span_adamio_c137db358c285f21())
	return swig_r
}

var Cali_Span Enum_SS_AI_CALI_MODE = _swig_getCali_Span()
func _swig_getCali_Cjc() (_swig_ret Enum_SS_AI_CALI_MODE) {
	var swig_r Enum_SS_AI_CALI_MODE
	swig_r = (Enum_SS_AI_CALI_MODE)(C._wrap_Cali_Cjc_adamio_c137db358c285f21())
	return swig_r
}

var Cali_Cjc Enum_SS_AI_CALI_MODE = _swig_getCali_Cjc()
type Enum_SS_AO_CALI_MODE int
func _swig_getCali_4mA() (_swig_ret Enum_SS_AO_CALI_MODE) {
	var swig_r Enum_SS_AO_CALI_MODE
	swig_r = (Enum_SS_AO_CALI_MODE)(C._wrap_Cali_4mA_adamio_c137db358c285f21())
	return swig_r
}

var Cali_4mA Enum_SS_AO_CALI_MODE = _swig_getCali_4mA()
func _swig_getCali_20mA() (_swig_ret Enum_SS_AO_CALI_MODE) {
	var swig_r Enum_SS_AO_CALI_MODE
	swig_r = (Enum_SS_AO_CALI_MODE)(C._wrap_Cali_20mA_adamio_c137db358c285f21())
	return swig_r
}

var Cali_20mA Enum_SS_AO_CALI_MODE = _swig_getCali_20mA()
func _swig_getCali_Trim() (_swig_ret Enum_SS_AO_CALI_MODE) {
	var swig_r Enum_SS_AO_CALI_MODE
	swig_r = (Enum_SS_AO_CALI_MODE)(C._wrap_Cali_Trim_adamio_c137db358c285f21())
	return swig_r
}

var Cali_Trim Enum_SS_AO_CALI_MODE = _swig_getCali_Trim()
type Enum_SS_tagPropertyAttribute int
func _swig_getReadOnly() (_swig_ret Enum_SS_tagPropertyAttribute) {
	var swig_r Enum_SS_tagPropertyAttribute
	swig_r = (Enum_SS_tagPropertyAttribute)(C._wrap_ReadOnly_adamio_c137db358c285f21())
	return swig_r
}

var ReadOnly Enum_SS_tagPropertyAttribute = _swig_getReadOnly()
func _swig_getWritable() (_swig_ret Enum_SS_tagPropertyAttribute) {
	var swig_r Enum_SS_tagPropertyAttribute
	swig_r = (Enum_SS_tagPropertyAttribute)(C._wrap_Writable_adamio_c137db358c285f21())
	return swig_r
}

var Writable Enum_SS_tagPropertyAttribute = _swig_getWritable()
func _swig_getModal() (_swig_ret Enum_SS_tagPropertyAttribute) {
	var swig_r Enum_SS_tagPropertyAttribute
	swig_r = (Enum_SS_tagPropertyAttribute)(C._wrap_Modal_adamio_c137db358c285f21())
	return swig_r
}

var Modal Enum_SS_tagPropertyAttribute = _swig_getModal()
func _swig_getNature() (_swig_ret Enum_SS_tagPropertyAttribute) {
	var swig_r Enum_SS_tagPropertyAttribute
	swig_r = (Enum_SS_tagPropertyAttribute)(C._wrap_Nature_adamio_c137db358c285f21())
	return swig_r
}

var Nature Enum_SS_tagPropertyAttribute = _swig_getNature()
type Enum_SS_tagErrorCode int
func _swig_getSuccess() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_Success_adamio_c137db358c285f21())
	return swig_r
}

var Success Enum_SS_tagErrorCode = _swig_getSuccess()
func _swig_getWarningIntrNotAvailable() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningIntrNotAvailable_adamio_c137db358c285f21())
	return swig_r
}

var WarningIntrNotAvailable Enum_SS_tagErrorCode = _swig_getWarningIntrNotAvailable()
func _swig_getWarningParamOutOfRange() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningParamOutOfRange_adamio_c137db358c285f21())
	return swig_r
}

var WarningParamOutOfRange Enum_SS_tagErrorCode = _swig_getWarningParamOutOfRange()
func _swig_getWarningPropValueOutOfRange() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningPropValueOutOfRange_adamio_c137db358c285f21())
	return swig_r
}

var WarningPropValueOutOfRange Enum_SS_tagErrorCode = _swig_getWarningPropValueOutOfRange()
func _swig_getWarningPropValueNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningPropValueNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var WarningPropValueNotSpted Enum_SS_tagErrorCode = _swig_getWarningPropValueNotSpted()
func _swig_getWarningPropValueConflict() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningPropValueConflict_adamio_c137db358c285f21())
	return swig_r
}

var WarningPropValueConflict Enum_SS_tagErrorCode = _swig_getWarningPropValueConflict()
func _swig_getWarningVrgOfGroupNotSame() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_WarningVrgOfGroupNotSame_adamio_c137db358c285f21())
	return swig_r
}

var WarningVrgOfGroupNotSame Enum_SS_tagErrorCode = _swig_getWarningVrgOfGroupNotSame()
func _swig_getErrorHandleNotValid() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorHandleNotValid_adamio_c137db358c285f21())
	return swig_r
}

var ErrorHandleNotValid Enum_SS_tagErrorCode = _swig_getErrorHandleNotValid()
func _swig_getErrorParamOutOfRange() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorParamOutOfRange_adamio_c137db358c285f21())
	return swig_r
}

var ErrorParamOutOfRange Enum_SS_tagErrorCode = _swig_getErrorParamOutOfRange()
func _swig_getErrorParamNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorParamNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorParamNotSpted Enum_SS_tagErrorCode = _swig_getErrorParamNotSpted()
func _swig_getErrorParamFmtUnexpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorParamFmtUnexpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorParamFmtUnexpted Enum_SS_tagErrorCode = _swig_getErrorParamFmtUnexpted()
func _swig_getErrorMemoryNotEnough() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorMemoryNotEnough_adamio_c137db358c285f21())
	return swig_r
}

var ErrorMemoryNotEnough Enum_SS_tagErrorCode = _swig_getErrorMemoryNotEnough()
func _swig_getErrorBufferIsNull() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorBufferIsNull_adamio_c137db358c285f21())
	return swig_r
}

var ErrorBufferIsNull Enum_SS_tagErrorCode = _swig_getErrorBufferIsNull()
func _swig_getErrorBufferTooSmall() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorBufferTooSmall_adamio_c137db358c285f21())
	return swig_r
}

var ErrorBufferTooSmall Enum_SS_tagErrorCode = _swig_getErrorBufferTooSmall()
func _swig_getErrorDataLenExceedLimit() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDataLenExceedLimit_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDataLenExceedLimit Enum_SS_tagErrorCode = _swig_getErrorDataLenExceedLimit()
func _swig_getErrorFuncNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorFuncNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorFuncNotSpted Enum_SS_tagErrorCode = _swig_getErrorFuncNotSpted()
func _swig_getErrorEventNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorEventNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorEventNotSpted Enum_SS_tagErrorCode = _swig_getErrorEventNotSpted()
func _swig_getErrorPropNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPropNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPropNotSpted Enum_SS_tagErrorCode = _swig_getErrorPropNotSpted()
func _swig_getErrorPropReadOnly() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPropReadOnly_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPropReadOnly Enum_SS_tagErrorCode = _swig_getErrorPropReadOnly()
func _swig_getErrorPropValueConflict() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPropValueConflict_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPropValueConflict Enum_SS_tagErrorCode = _swig_getErrorPropValueConflict()
func _swig_getErrorPropValueOutOfRange() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPropValueOutOfRange_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPropValueOutOfRange Enum_SS_tagErrorCode = _swig_getErrorPropValueOutOfRange()
func _swig_getErrorPropValueNotSpted() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPropValueNotSpted_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPropValueNotSpted Enum_SS_tagErrorCode = _swig_getErrorPropValueNotSpted()
func _swig_getErrorPrivilegeNotHeld() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPrivilegeNotHeld_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPrivilegeNotHeld Enum_SS_tagErrorCode = _swig_getErrorPrivilegeNotHeld()
func _swig_getErrorPrivilegeNotAvailable() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorPrivilegeNotAvailable_adamio_c137db358c285f21())
	return swig_r
}

var ErrorPrivilegeNotAvailable Enum_SS_tagErrorCode = _swig_getErrorPrivilegeNotAvailable()
func _swig_getErrorDriverNotFound() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDriverNotFound_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDriverNotFound Enum_SS_tagErrorCode = _swig_getErrorDriverNotFound()
func _swig_getErrorDriverVerMismatch() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDriverVerMismatch_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDriverVerMismatch Enum_SS_tagErrorCode = _swig_getErrorDriverVerMismatch()
func _swig_getErrorDriverCountExceedLimit() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDriverCountExceedLimit_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDriverCountExceedLimit Enum_SS_tagErrorCode = _swig_getErrorDriverCountExceedLimit()
func _swig_getErrorDeviceNotOpened() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDeviceNotOpened_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDeviceNotOpened Enum_SS_tagErrorCode = _swig_getErrorDeviceNotOpened()
func _swig_getErrorDeviceNotExist() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDeviceNotExist_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDeviceNotExist Enum_SS_tagErrorCode = _swig_getErrorDeviceNotExist()
func _swig_getErrorDeviceUnrecognized() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDeviceUnrecognized_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDeviceUnrecognized Enum_SS_tagErrorCode = _swig_getErrorDeviceUnrecognized()
func _swig_getErrorConfigDataLost() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorConfigDataLost_adamio_c137db358c285f21())
	return swig_r
}

var ErrorConfigDataLost Enum_SS_tagErrorCode = _swig_getErrorConfigDataLost()
func _swig_getErrorFuncNotInited() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorFuncNotInited_adamio_c137db358c285f21())
	return swig_r
}

var ErrorFuncNotInited Enum_SS_tagErrorCode = _swig_getErrorFuncNotInited()
func _swig_getErrorFuncBusy() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorFuncBusy_adamio_c137db358c285f21())
	return swig_r
}

var ErrorFuncBusy Enum_SS_tagErrorCode = _swig_getErrorFuncBusy()
func _swig_getErrorIntrNotAvailable() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorIntrNotAvailable_adamio_c137db358c285f21())
	return swig_r
}

var ErrorIntrNotAvailable Enum_SS_tagErrorCode = _swig_getErrorIntrNotAvailable()
func _swig_getErrorDmaNotAvailable() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDmaNotAvailable_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDmaNotAvailable Enum_SS_tagErrorCode = _swig_getErrorDmaNotAvailable()
func _swig_getErrorDeviceIoTimeOut() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorDeviceIoTimeOut_adamio_c137db358c285f21())
	return swig_r
}

var ErrorDeviceIoTimeOut Enum_SS_tagErrorCode = _swig_getErrorDeviceIoTimeOut()
func _swig_getErrorSignatureNotMatch() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorSignatureNotMatch_adamio_c137db358c285f21())
	return swig_r
}

var ErrorSignatureNotMatch Enum_SS_tagErrorCode = _swig_getErrorSignatureNotMatch()
func _swig_getErrorUndefined() (_swig_ret Enum_SS_tagErrorCode) {
	var swig_r Enum_SS_tagErrorCode
	swig_r = (Enum_SS_tagErrorCode)(C._wrap_ErrorUndefined_adamio_c137db358c285f21())
	return swig_r
}

var ErrorUndefined Enum_SS_tagErrorCode = _swig_getErrorUndefined()
func ADAMDrvOpen(arg1 *int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ADAMDrvOpen_adamio_c137db358c285f21(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func ADAMDrvClose(arg1 *int) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	swig_r = (uint)(C._wrap_ADAMDrvClose_adamio_c137db358c285f21(C.swig_voidp(_swig_i_0)))
	return swig_r
}

func SYS_GetNodeID(arg1 int, arg2 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uint)(C._wrap_SYS_GetNodeID_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func SYS_GetModuleID(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SYS_GetModuleID_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func SYS_GetModuleName(arg1 int, arg2 uint16, arg3 string) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_SYS_GetModuleName_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func AI_GetChannelTotal(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_GetChannelTotal_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}
/*
func AI_GetChannelEnabled(arg1 int, arg2 uint16, arg3 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_GetChannelEnabled_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}
*/

func AI_GetChannelEnabled(arg1 int, arg2 uint16, arg3 unsafe.Pointer) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	//swig_r = (uint)(C._wrap_AI_GetChannelEnabled_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	swig_r = (uint)(C._wrap_AI_GetChannelEnabled_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), (*C.char)(_swig_i_2)))
	return swig_r
}

func AI_SetChannelEnabled(arg1 int, arg2 uint16, arg3 unsafe.Pointer) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_SetChannelEnabled_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), (*C.char)(_swig_i_2)))
	return swig_r
}

func AI_GetInputRange(arg1 int, arg2 uint16, arg3 uint16, arg4 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AI_GetInputRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func AI_SetInputRange(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AI_SetInputRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func AI_GetRangeIntegrationTime(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_GetRangeIntegrationTime_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func AI_SetRangeIntegrationTime(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_SetRangeIntegrationTime_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func AI_GetDataFormat(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_GetDataFormat_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func AI_SetDataFormat(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AI_SetDataFormat_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func AI_GetValues(arg1 int, arg2 uint16, arg3 unsafe.Pointer, arg4 unsafe.Pointer) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AI_GetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), (*C.uint16_t)(_swig_i_2), (*C.double)(_swig_i_3) ))
	return swig_r
}

func AI_GetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 uintptr, arg5 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_AI_GetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.uintptr_t(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func AI_Calibration(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AI_Calibration_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func AI_Calibration_CJC(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 float32) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_AI_Calibration_CJC_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.float(_swig_i_4)))
	return swig_r
}

func AO_GetChannelTotal(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AO_GetChannelTotal_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func AO_GetOutputRange(arg1 int, arg2 uint16, arg3 uint16, arg4 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_GetOutputRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func AO_SetOutputRange(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_SetOutputRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func AO_GetStartup(arg1 int, arg2 uint16, arg3 uint16, arg4 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_GetStartup_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func AO_SetStartup(arg1 int, arg2 uint16, arg3 uint16, arg4 float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_SetStartup_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func AO_GetValues(arg1 int, arg2 uint16, arg3 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AO_GetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func AO_GetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_GetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func AO_SetValues(arg1 int, arg2 uint16, arg3 *float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AO_SetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func AO_SetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 float64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_SetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.double(_swig_i_3)))
	return swig_r
}

func AO_Calibration_4mA(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AO_Calibration_4mA_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func AO_Calibration_20mA(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_AO_Calibration_20mA_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func AO_Calibration_Trim(arg1 int, arg2 uint16, arg3 uint16, arg4 int64) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_AO_Calibration_Trim_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_type_2(_swig_i_3)))
	return swig_r
}

func DIO_GetChannelTotal(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DIO_GetChannelTotal_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func DI_GetValues(arg1 int, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DI_GetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func DI_GetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_DI_GetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func DIO_GetUniversalStatus(arg1 int, arg2 uint16, arg3 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DIO_GetUniversalStatus_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func DI_GetInvert(arg1 int, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DI_GetInvert_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func DI_SetInvert(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_DI_SetInvert_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func DO_SetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_DO_SetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C._Bool(_swig_i_3)))
	return swig_r
}

func DO_SetValues(arg1 int, arg2 uint16, arg3 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DO_SetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func DO_GetValues(arg1 int, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_DO_GetValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func CNT_GetValue(arg1 int, arg2 uint16, arg3 uint16, arg4 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_ClearValue(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_ClearValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func CNT_GetRange(arg1 int, arg2 uint16, arg3 uint16, arg4 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetRange(arg1 uint, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetRange_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func CNT_GetFilter(arg1 int, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_GetFilter_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func CNT_SetFilter(arg1 int, arg2 uint16, arg3 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_SetFilter_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func CNT_GetStartup(arg1 int, arg2 uint16, arg3 uint16, arg4 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetStartup_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetStartup(arg1 int, arg2 uint16, arg3 uint16, arg4 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetStartup_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func CNT_GetState(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetState_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetState(arg1 int, arg2 uint16, arg3 uint16, arg4 bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetState_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C._Bool(_swig_i_3)))
	return swig_r
}

func CNT_GetOverflow(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetOverflow_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_ClearOverflow(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_ClearOverflow_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func CNT_GetAlarmFlag(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetAlarmFlag_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_ClearAlarmFlag(arg1 int, arg2 uint16, arg3 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_ClearAlarmFlag_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2)))
	return swig_r
}

func CNT_GetAlarmType(arg1 uint, arg2 uint16, arg3 uint16, arg4 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetAlarmType_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetAlarmType(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetAlarmType_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func CNT_GetAlarmEnable(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetAlarmEnable_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetAlarmEnable(arg1 int, arg2 uint16, arg3 uint16, arg4 bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetAlarmEnable_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C._Bool(_swig_i_3)))
	return swig_r
}

func CNT_GetAlarmMap(arg1 int, arg2 uint16, arg3 uint16, arg4 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetAlarmMap_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetAlarmMap(arg1 uint, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetAlarmMap_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func CNT_GetAlarmLimit(arg1 int, arg2 uint16, arg3 uint16, arg4 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetAlarmLimit_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetAlarmLimit(arg1 int, arg2 uint16, arg3 uint16, arg4 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetAlarmLimit_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_intgo(_swig_i_3)))
	return swig_r
}

func CNT_GetDoValue(arg1 int, arg2 uint16, arg3 uint16, arg4 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_GetDoValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.swig_voidp(_swig_i_3)))
	return swig_r
}

func CNT_SetDoValue(arg1 int, arg2 uint16, arg3 uint16, arg4 bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_SetDoValue_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C._Bool(_swig_i_3)))
	return swig_r
}

func CNT_GetDoValues(arg1 int, arg2 uint16, arg3 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_GetDoValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func CNT_SetDoValues(arg1 int, arg2 uint16, arg3 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_SetDoValues_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.char(_swig_i_2)))
	return swig_r
}

func CNT_GetFreqAcqTime(arg1 int, arg2 uint16, arg3 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_GetFreqAcqTime_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func CNT_SetFreqAcqTime(arg1 int, arg2 uint16, arg3 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_SetFreqAcqTime_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func CNT_GetRemoteAlarmFlag(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_CNT_GetRemoteAlarmFlag_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func CNT_ClearRemoteAlarmFlag(arg1 int, arg2 uint16, arg3 uint16, arg4 byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (uint)(C._wrap_CNT_ClearRemoteAlarmFlag_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3)))
	return swig_r
}

func CNT_GetRemoteAlarmEnable(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 *bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_CNT_GetRemoteAlarmEnable_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func CNT_SetRemoteAlarmEnable(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 bool) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_CNT_SetRemoteAlarmEnable_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C._Bool(_swig_i_4)))
	return swig_r
}

func CNT_GetRemoteAlarmMap(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 *uint16, arg6 *uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (uint)(C._wrap_CNT_GetRemoteAlarmMap_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.swig_voidp(_swig_i_4), C.swig_voidp(_swig_i_5)))
	return swig_r
}

func CNT_SetRemoteAlarmMap(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 uint16, arg6 uint16) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (uint)(C._wrap_CNT_SetRemoteAlarmMap_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.short(_swig_i_4), C.short(_swig_i_5)))
	return swig_r
}

func CNT_GetRemoteAlarmLimit(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 *uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_CNT_GetRemoteAlarmLimit_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.swig_voidp(_swig_i_4)))
	return swig_r
}

func CNT_SetRemoteAlarmLimit(arg1 int, arg2 uint16, arg3 uint16, arg4 byte, arg5 uint) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (uint)(C._wrap_CNT_SetRemoteAlarmLimit_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.short(_swig_i_2), C.char(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func CNT_GetFwVersion(arg1 int, arg2 uint16, arg3 *byte) (_swig_ret uint) {
	var swig_r uint
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (uint)(C._wrap_CNT_GetFwVersion_adamio_c137db358c285f21(C.swig_intgo(_swig_i_0), C.short(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}


