/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: adamio.i */

#define SWIGMODULE adamio
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef int intgo;
typedef unsigned int uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


/* Includes the header in the wrapper code */
#include "bdaqadamio.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_adamio_c137db358c285f21(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_adamio_c137db358c285f21(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5017_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5017;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5018_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5018;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5013A_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5013A;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5013B_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5013B;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5017H_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5017H;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5017UH_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5017UH;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5018P_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5018P;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5024_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5024;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5050_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5050;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5051_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5051;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5052_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5052;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5053_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5053;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5055_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5055;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5056_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5056;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5057_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5057;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5060_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5060;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5068_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5068;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5069_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5069;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5080_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5080;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_5081_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_5081;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_UNDEFINE_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_UNDEFINE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_MODULEID_MASK_adamio_c137db358c285f21() {
  enum tagModuleId result;
  intgo _swig_go_result;
  
  
  result = MODULEID_MASK;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Hz_60_adamio_c137db358c285f21() {
  enum tagAiIntegrationTime result;
  intgo _swig_go_result;
  
  
  result = Hz_60;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Hz_50_adamio_c137db358c285f21() {
  enum tagAiIntegrationTime result;
  intgo _swig_go_result;
  
  
  result = Hz_50;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_OMIT_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_OMIT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg15To15_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg15To15;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg10To10_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg10To10;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg5To5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg5To5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg2pt5To2pt5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg2pt5To2pt5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg1pt25To1pt25_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg1pt25To1pt25;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg1To1_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg1To1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To15_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To15;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To10_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To10;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To2pt5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To2pt5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To1pt25_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To1pt25;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_0To1_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_0To1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg625To625_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg625To625;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg500To500_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg500To500;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg312pt5To312pt5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg312pt5To312pt5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg200To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg200To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg150To150_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg150To150;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg100To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg100To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg50To50_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg50To50;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg30To30_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg30To30;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg20To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg20To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg15To15_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg15To15;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg10To10_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg10To10;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_Neg5To5_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_Neg5To5;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To625_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To625;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To500_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To500;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To150_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To150;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To50_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To50;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To15_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To15;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mV_0To10_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mV_0To10;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mA_Neg20To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mA_Neg20To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mA_0To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mA_0To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mA_4To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mA_4To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_mA_0To24_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = mA_0To24;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg2To2_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg2To2;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg4To4_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg4To4;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_Neg20To20_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_Neg20To20;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Jtype_0To760C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Jtype_0To760C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ktype_0To1370C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ktype_0To1370C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ttype_Neg100To400C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ttype_Neg100To400C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Etype_0To1000C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Etype_0To1000C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Rtype_500To1750C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Rtype_500To1750C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Stype_500To1750C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Stype_500To1750C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Btype_500To1800C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Btype_500To1800C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_Neg50To150_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_Neg50To150;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_Neg200To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_Neg200To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_0To400_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_0To400;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_Neg50To150_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_Neg50To150;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_Neg100To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_Neg100To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_0To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_0To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt385_0To600_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt385_0To600;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_Neg100To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_Neg100To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_0To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_0To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_0To600_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_0To600;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_0To400_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_0To400;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt392_Neg200To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt392_Neg200To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Pt1000_Neg40To160_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Pt1000_Neg40To160;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Balcon500_Neg30To120_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Balcon500_Neg30To120;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ni518_Neg80To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ni518_Neg80To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ni518_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ni518_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ni508_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ni508_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ni508_Neg50To200_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ni508_Neg50To200;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Thermistor_3K_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Thermistor_3K_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Thermistor_10K_0To100_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Thermistor_10K_0To100;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Jtype_Neg210To1200C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Jtype_Neg210To1200C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ktype_Neg270To1372C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ktype_Neg270To1372C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ttype_Neg270To400C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ttype_Neg270To400C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Etype_Neg270To1000C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Etype_Neg270To1000C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Rtype_Neg50To1768C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Rtype_Neg50To1768C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Stype_Neg50To1768C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Stype_Neg50To1768C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Btype_40To1820C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Btype_40To1820C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Jtype_Neg210To870C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Jtype_Neg210To870C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Rtype_0To1768C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Rtype_0To1768C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Stype_0To1768C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Stype_0To1768C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ttype_Neg20To135C_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = Ttype_Neg20To135C;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_UserCustomizedVrgStart_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = UserCustomizedVrgStart;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_UserCustomizedVrgEnd_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = UserCustomizedVrgEnd;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_ExternalRefBipolar_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_ExternalRefBipolar;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_V_ExternalRefUnipolar_adamio_c137db358c285f21() {
  enum tagValueRange result;
  intgo _swig_go_result;
  
  
  result = V_ExternalRefUnipolar;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ContrMod_Bi_DIR_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = ContrMod_Bi_DIR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ContrMod_UP_DOWN_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = ContrMod_UP_DOWN;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ContrMod_UP_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = ContrMod_UP;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ContrMod_Freq_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = ContrMod_Freq;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AbPhaseX1_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = AbPhaseX1;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AbPhaseX2_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = AbPhaseX2;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_AbPhaseX4_adamio_c137db358c285f21() {
  enum tagSignalCountingType result;
  intgo _swig_go_result;
  
  
  result = AbPhaseX4;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EngineerUnit_adamio_c137db358c285f21() {
  enum tagAIDataUnit result;
  intgo _swig_go_result;
  
  
  result = EngineerUnit;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Percent_adamio_c137db358c285f21() {
  enum tagAIDataUnit result;
  intgo _swig_go_result;
  
  
  result = Percent;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TwosComplementHex_adamio_c137db358c285f21() {
  enum tagAIDataUnit result;
  intgo _swig_go_result;
  
  
  result = TwosComplementHex;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Ohms_adamio_c137db358c285f21() {
  enum tagAIDataUnit result;
  intgo _swig_go_result;
  
  
  result = Ohms;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Unknown_adamio_c137db358c285f21() {
  enum tagAIDataUnit result;
  intgo _swig_go_result;
  
  
  result = Unknown;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_Zero_adamio_c137db358c285f21() {
  enum AI_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_Zero;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_Span_adamio_c137db358c285f21() {
  enum AI_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_Span;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_Cjc_adamio_c137db358c285f21() {
  enum AI_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_Cjc;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_4mA_adamio_c137db358c285f21() {
  enum AO_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_4mA;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_20mA_adamio_c137db358c285f21() {
  enum AO_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_20mA;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Cali_Trim_adamio_c137db358c285f21() {
  enum AO_CALI_MODE result;
  intgo _swig_go_result;
  
  
  result = Cali_Trim;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ReadOnly_adamio_c137db358c285f21() {
  enum tagPropertyAttribute result;
  intgo _swig_go_result;
  
  
  result = ReadOnly;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Writable_adamio_c137db358c285f21() {
  enum tagPropertyAttribute result;
  intgo _swig_go_result;
  
  
  result = Writable;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Modal_adamio_c137db358c285f21() {
  enum tagPropertyAttribute result;
  intgo _swig_go_result;
  
  
  result = Modal;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Nature_adamio_c137db358c285f21() {
  enum tagPropertyAttribute result;
  intgo _swig_go_result;
  
  
  result = Nature;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_Success_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = Success;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningIntrNotAvailable_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningIntrNotAvailable;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningParamOutOfRange_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningParamOutOfRange;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningPropValueOutOfRange_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningPropValueOutOfRange;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningPropValueNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningPropValueNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningPropValueConflict_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningPropValueConflict;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_WarningVrgOfGroupNotSame_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = WarningVrgOfGroupNotSame;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorHandleNotValid_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorHandleNotValid;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorParamOutOfRange_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorParamOutOfRange;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorParamNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorParamNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorParamFmtUnexpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorParamFmtUnexpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorMemoryNotEnough_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorMemoryNotEnough;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorBufferIsNull_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorBufferIsNull;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorBufferTooSmall_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorBufferTooSmall;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDataLenExceedLimit_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDataLenExceedLimit;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorFuncNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorFuncNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorEventNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorEventNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPropNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPropNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPropReadOnly_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPropReadOnly;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPropValueConflict_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPropValueConflict;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPropValueOutOfRange_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPropValueOutOfRange;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPropValueNotSpted_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPropValueNotSpted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPrivilegeNotHeld_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPrivilegeNotHeld;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorPrivilegeNotAvailable_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorPrivilegeNotAvailable;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDriverNotFound_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDriverNotFound;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDriverVerMismatch_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDriverVerMismatch;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDriverCountExceedLimit_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDriverCountExceedLimit;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDeviceNotOpened_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDeviceNotOpened;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDeviceNotExist_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDeviceNotExist;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDeviceUnrecognized_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDeviceUnrecognized;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorConfigDataLost_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorConfigDataLost;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorFuncNotInited_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorFuncNotInited;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorFuncBusy_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorFuncBusy;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorIntrNotAvailable_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorIntrNotAvailable;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDmaNotAvailable_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDmaNotAvailable;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorDeviceIoTimeOut_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorDeviceIoTimeOut;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorSignatureNotMatch_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorSignatureNotMatch;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ErrorUndefined_adamio_c137db358c285f21() {
  enum tagErrorCode result;
  intgo _swig_go_result;
  
  
  result = ErrorUndefined;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ADAMDrvOpen_adamio_c137db358c285f21(intgo *_swig_go_0) {
  int *arg1 = (int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(int **)&_swig_go_0; 
  
  result = (unsigned int)ADAMDrvOpen(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ADAMDrvClose_adamio_c137db358c285f21(intgo *_swig_go_0) {
  int *arg1 = (int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = *(int **)&_swig_go_0; 
  
  result = (unsigned int)ADAMDrvClose(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SYS_GetNodeID_adamio_c137db358c285f21(intgo _swig_go_0, short *_swig_go_1) {
  int arg1 ;
  unsigned short *arg2 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = *(unsigned short **)&_swig_go_1; 
  
  result = (unsigned int)SYS_GetNodeID(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SYS_GetModuleID_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)SYS_GetModuleID(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_SYS_GetModuleName_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, _gostring_ _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  char *arg3 = (char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (unsigned int)SYS_GetModuleName(arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_AI_GetChannelTotal_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)AI_GetChannelTotal(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetChannelEnabled_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, char *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = _swig_go_2;
  
  result = (unsigned int)AI_GetChannelEnabled(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_SetChannelEnabled_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, char *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  //arg3 = *(unsigned char **)&_swig_go_2;
  arg3 = _swig_go_2;
  
  result = (unsigned int)AI_SetChannelEnabled(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetInputRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (unsigned int)AI_GetInputRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_SetInputRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)AI_SetInputRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetRangeIntegrationTime_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)AI_GetRangeIntegrationTime(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_SetRangeIntegrationTime_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)AI_SetRangeIntegrationTime(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetDataFormat_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)AI_GetDataFormat(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_SetDataFormat_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)AI_SetDataFormat(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, unsigned short *_swig_go_2, double *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  void *arg3 = (void *) 0 ;
  double *arg4 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = _swig_go_2;
  arg4 = _swig_go_3;
  
  result = (unsigned int)AI_GetValues(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_GetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, void *_swig_go_3, double *_swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  void *arg4 = (void *) 0 ;
  double *arg5 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  arg5 = *(double **)&_swig_go_4; 
  
  result = (unsigned int)AI_GetValue(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_Calibration_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)AI_Calibration(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AI_Calibration_CJC_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, float _swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  float arg5 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = (float)_swig_go_4; 
  
  result = (unsigned int)AI_Calibration_CJC(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_GetChannelTotal_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)AO_GetChannelTotal(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_GetOutputRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (unsigned int)AO_GetOutputRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_SetOutputRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)AO_SetOutputRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_GetStartup_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, double *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  double *arg4 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(double **)&_swig_go_3; 
  
  result = (unsigned int)AO_GetStartup(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_SetStartup_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, double _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  double arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  
  result = (unsigned int)AO_SetStartup(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_GetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, double *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  double *arg3 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  
  result = (unsigned int)AO_GetValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_GetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, double *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  double *arg4 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(double **)&_swig_go_3; 
  
  result = (unsigned int)AO_GetValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_SetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, double *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  double *arg3 = (double *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(double **)&_swig_go_2; 
  
  result = (unsigned int)AO_SetValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_SetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, double _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  double arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (double)_swig_go_3; 
  
  result = (unsigned int)AO_SetValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_Calibration_4mA_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)AO_Calibration_4mA(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_Calibration_20mA_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)AO_Calibration_20mA(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_AO_Calibration_Trim_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, long long _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  long arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (long)_swig_go_3; 
  
  result = (unsigned int)AO_Calibration_Trim(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DIO_GetChannelTotal_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)DIO_GetChannelTotal(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DI_GetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned int **)&_swig_go_2; 
  
  result = (unsigned int)DI_GetValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DI_GetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)DI_GetValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DIO_GetUniversalStatus_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short *arg3 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned short **)&_swig_go_2; 
  
  result = (unsigned int)DIO_GetUniversalStatus(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DI_GetInvert_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned int **)&_swig_go_2; 
  
  result = (unsigned int)DI_GetInvert(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DI_SetInvert_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)DI_SetInvert(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DO_SetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (unsigned int)DO_SetValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DO_SetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  
  result = (unsigned int)DO_SetValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_DO_GetValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned int **)&_swig_go_2; 
  
  result = (unsigned int)DO_GetValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int *arg4 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned int **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_ClearValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)CNT_ClearValue(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetRange_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  unsigned int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)CNT_SetRange(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetFilter_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned int **)&_swig_go_2; 
  
  result = (unsigned int)CNT_GetFilter(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetFilter_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  
  result = (unsigned int)CNT_SetFilter(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetStartup_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int *arg4 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned int **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetStartup(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetStartup_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  
  result = (unsigned int)CNT_SetStartup(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetState_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetState(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetState_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (unsigned int)CNT_SetState(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetOverflow_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetOverflow(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_ClearOverflow_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)CNT_ClearOverflow(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetAlarmFlag_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetAlarmFlag(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_ClearAlarmFlag_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  
  result = (unsigned int)CNT_ClearAlarmFlag(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetAlarmType_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  unsigned int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetAlarmType(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetAlarmType_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)CNT_SetAlarmType(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetAlarmEnable_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetAlarmEnable(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetAlarmEnable_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (unsigned int)CNT_SetAlarmEnable(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetAlarmMap_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned char **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetAlarmMap(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetAlarmMap_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  unsigned int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)CNT_SetAlarmMap(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetAlarmLimit_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int *arg4 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(unsigned int **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetAlarmLimit(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetAlarmLimit_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, intgo _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned int arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned int)_swig_go_3; 
  
  result = (unsigned int)CNT_SetAlarmLimit(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetDoValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool *_swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool *arg4 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = *(bool **)&_swig_go_3; 
  
  result = (unsigned int)CNT_GetDoValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetDoValue_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, bool _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  bool arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (bool)_swig_go_3; 
  
  result = (unsigned int)CNT_SetDoValue(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetDoValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, char *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned char **)&_swig_go_2; 
  
  result = (unsigned int)CNT_GetDoValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetDoValues_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, char _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned char arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned char)_swig_go_2; 
  
  result = (unsigned int)CNT_SetDoValues(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetFreqAcqTime_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned int **)&_swig_go_2; 
  
  result = (unsigned int)CNT_GetFreqAcqTime(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetFreqAcqTime_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, intgo _swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned int arg3 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned int)_swig_go_2; 
  
  result = (unsigned int)CNT_SetFreqAcqTime(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetRemoteAlarmFlag_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, bool *_swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  bool *arg5 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = *(bool **)&_swig_go_4; 
  
  result = (unsigned int)CNT_GetRemoteAlarmFlag(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_ClearRemoteAlarmFlag_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  
  result = (unsigned int)CNT_ClearRemoteAlarmFlag(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetRemoteAlarmEnable_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, bool *_swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  bool *arg5 = (bool *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = *(bool **)&_swig_go_4; 
  
  result = (unsigned int)CNT_GetRemoteAlarmEnable(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetRemoteAlarmEnable_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, bool _swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  bool arg5 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = (bool)_swig_go_4; 
  
  result = (unsigned int)CNT_SetRemoteAlarmEnable(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetRemoteAlarmMap_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, short *_swig_go_4, short *_swig_go_5) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned short *arg5 = (unsigned short *) 0 ;
  unsigned short *arg6 = (unsigned short *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = *(unsigned short **)&_swig_go_4; 
  arg6 = *(unsigned short **)&_swig_go_5; 
  
  result = (unsigned int)CNT_GetRemoteAlarmMap(arg1,arg2,arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetRemoteAlarmMap_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, short _swig_go_4, short _swig_go_5) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned short arg5 ;
  unsigned short arg6 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = (unsigned short)_swig_go_4; 
  arg6 = (unsigned short)_swig_go_5; 
  
  result = (unsigned int)CNT_SetRemoteAlarmMap(arg1,arg2,arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetRemoteAlarmLimit_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, intgo *_swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int *arg5 = (unsigned int *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = *(unsigned int **)&_swig_go_4; 
  
  result = (unsigned int)CNT_GetRemoteAlarmLimit(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_SetRemoteAlarmLimit_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, short _swig_go_2, char _swig_go_3, intgo _swig_go_4) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned short arg3 ;
  unsigned char arg4 ;
  unsigned int arg5 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = (unsigned short)_swig_go_2; 
  arg4 = (unsigned char)_swig_go_3; 
  arg5 = (unsigned int)_swig_go_4; 
  
  result = (unsigned int)CNT_SetRemoteAlarmLimit(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_CNT_GetFwVersion_adamio_c137db358c285f21(intgo _swig_go_0, short _swig_go_1, char *_swig_go_2) {
  int arg1 ;
  unsigned short arg2 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = (unsigned short)_swig_go_1; 
  arg3 = *(unsigned char **)&_swig_go_2; 
  
  result = (unsigned int)CNT_GetFwVersion(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

